export { default as About } from './About'
export { default as Header } from './Header'
export { default as Hobbies } from './Hobbies'
export { default as Home } from './Home'
export { default as Projects } from './Projects'
export { default as Skills } from './Skills'
